sudo: false

language: php

env:
  global:
  - secure: GZuBoHlpcrgIBwu4Y254Enq2ahpC36jnyXhB2YJLI1+3xqmf4qq7IjxuOLmZkIHA/VCls7L7+avarrw/lT/z7ZeaCVJ0x/oK34WcHm84dP21wIe+jPlom7TN1leWTNbqAXfrrYvQJGEF9JweKw5WWRBhvXtgXiT2ckvBijuVAdA=
  - secure: DAcE4hAgVJPQOU+qvU77S6rseu+9Mc9sKamPZRUEVNFY+xU/B5ZuVivRJd0VtGHzgRqsZXRMXih96Nau5TSSxV28C/Sd8bnu0VzA1UnV07uKhwOyb7vRi+KbdNN0ICFPuqw7RFgoqytV4BpKRer+ZQDohpN7XdiBumrrrBREZyk=
  - secure: OgtWjiebuZowAhHEthCbFocW/4LnapqqXNlZr9+KI93IgpHoubiimO0WSNL3S2//CO47qyuENNYOmUQWlXcQ1qIlhB/fzZ911CDU0oT2f1CSFihoUemRXRXYbuXHD52kT7eQttqHYCVmPWeH++B5r7kzYa2kNgP9fCJ3Vk29nCc=
  - secure: h3rVFMIzYoTE9Y/WEhVUKV1LU7Oq5m0MI/2ufTTR+yFrX9qIX08QbE6ZnDvCihOVDCDT0rx6AcnaB+u1ay2gTsedmHw44GJbI37xiLFx+C9F6edXtTjlUkF/WG/06N/NYmb1lsxb2sgmMXl8vOcT1CpBnvxr07eDpzGG534fdXQ=

matrix:
  include:
    - php: 5.2
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.2
      env: WP_VERSION=4.0 WP_MULTISITE=1
    - php: 5.3
      env: WP_VERSION=4.0
    - php: 5.4
      env: WP_VERSION=4.0
    - php: 5.5
      env: WP_VERSION=4.0
    - php: 5.6
      env: WP_VERSION=4.0 COVERAGE=1 GRUNT=1
    - php: 7.0
      env: WP_VERSION=4.0
    - php: hhvm
      env: WP_VERSION=4.0
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_script:
  - bash bin/travis-before_script

script:
  - bash bin/travis-script

after_success:
  - bash bin/travis-after_success
